const
  express = require('express');

require('dotenv').config();

var app = express();
app.set('port', process.env.PORT || 9000);

/* Config values can be set as environment variables
 * APP_SECRET - App dashboard
 * VERIFY_TOKEN - arbitrary value to verify webhook
 * ACCESS_TOKEN - generated by creating a Custom Integration https://developers.facebook.com/docs/workplace/custom-integrations-new
 */

const
  APP_SECRET = process.env.APP_SECRET,
  VERIFY_TOKEN = process.env.VERIFY_TOKEN,
  ACCESS_TOKEN = process.env.ACCESS_TOKEN;

if (!(APP_SECRET && VERIFY_TOKEN && ACCESS_TOKEN)) {
  console.error('Missing configuration values');
  process.exit(1);
}

app.get('/', function (req, res) {
  if (req.query['hub.mode'] === 'subscribe' &&
    req.query['hub.verify_token'] === VERIFY_TOKEN) {
    console.log('Validating webhook');
    res.status(200).send(req.query['hub.challenge']);
  } else {
    console.error('Failed validation. Make sure the validation tokens match.');
    res.sendStatus(403);
  }
});

app.post('/', function (req, res) {
  try {
    var data = req.body;
    switch (data.object) {
      case 'page':
        processPageEvents(data);
        break;
      case 'group':
        processGroupEvents(data);
        break;
      case 'user':
        processUserEvents(data);
        break;
      case 'workplace_security':
        processWorkplaceSecurityEvents(data);
        break;
      default:
        console.log('Unhandled Webhook Object', data.object);
    }
  } catch (e) {
    console.error(e);
    // Always respond with 200 OK to avoid retries
    res.sendStatus(200);
  }
});

function processGroupEvents(data) {
  data.entry.forEach(function (entry) {
    let group_id = entry.id;
    entry.changes.forEach(function (change) {
      console.log('Group change', group_id, change);
    });
  });
}

/* Verify that the callback came from Facebook.
 */
function verifyRequestSignature(req, res, buf) {
  var signature = req.headers['x-hub-signature'];

  if (!signature) {
    // Should throw an error
    console.error('Couldn\'t validate the signature');
  } else {
    var elements = signature.split('=');
    var signatureHash = element[1];

    var expectedHash = crypto.createHmac('sha1', APP_SECRET).update(buf).digest('hex');
    if (signatureHash != expectedHash) {
      throw new Error('Couldn\'t validate the request signature.');
    }
  }
}

app.listen(app.get('port'), function () {
  console.log('Node app is running on port', app.get('port'));
});
module.exports = app;


