# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate-code:
    name: Validate code style
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: node

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm packages
        uses: bahmutov/npm-install@v1
        with:
          working-directory: node

      - name: Format code
        working-directory: node
        run: npm run format:check --if-present

      - name: Lint code
        working-directory: node
        run: npm run lint --if-present

  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm packages
        uses: bahmutov/npm-install@v1
        with:
          working-directory: node

      - name: Build
        working-directory: node
        run: npm run build --if-present

      - name: Test
        working-directory: node
        run: npm run test --if-present
